---
- name: connect indexers together
  set_fact:
    indexers: "{{ indexers + [item + ':' + hostvars[item]['input_port']|string] }}"
  with_items: "{{ groups['indexer'] }}"

- debug:
    msg: "Indexers are: {{indexers}}."

- name: connect string
  set_fact:
    indexeroutput: "{{indexers|join(',')}}"

- debug:
    msg: "Forwarding data to {{indexeroutput}} in splunk servers."

- name: Add default outputs configuration
  lineinfile:
    path: /opt/splunk/etc/system/local/outputs.conf
    line: |
      #[tcpout]
      #defaultGroup = indexers

      #[tcpout:indexers]
      #server = {{indexeroutput}}

      [indexer_discovery:idxes]
      pass4SymmKey = idxdiscovery
      master_uri = https://{{ groups['cluster_master'][0] }}:8089
      manager_uri = https://{{ groups['cluster_master'][0] }}:8089

      [tcpout:idxgroup]
      indexerDiscovery = idxes
      useACK = true

      [tcpout]
      defaultGroup = idxgroup
    create: yes

- name: Add default deployer
  lineinfile:
    path: /opt/splunk/etc/system/local/server.conf
    line: |

      [shclustering]
      pass4SymmKey = {{ cluster_pass }}
      cluster_label = {{ shc_cluster_label }}
    create: yes

- name: Give splunk owner rights to the whole folder
  file:
    path: /opt/splunk
    state: directory
    recurse: yes
    owner: splunk
    group: splunk
