---
- name: Collect the system facts under ansible_facts.fqdn
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - network

- name: initialize the search head cluster
  command: /opt/splunk/bin/splunk init shcluster-config -auth admin:{{splunk_admin_password}} -mgmt_uri https://{{ansible_facts.eth0.ipv4.address}}:8089 -replication_port {{replication_port}} -replication_factor {{searchheads}} -conf_deploy_fetch_url https://{{groups['deployer'][0]}}:8089 -secret {{cluster_pass}} -shcluster_label {{shc_cluster_label}}
  become: true
  become_user: splunk
  async: 90
  poll: 5

- name: restart Splunk service
  command: /opt/splunk/bin/splunk start
  become: true
  become_user: splunk
  async: 300
  poll: 5
