---
- hosts: all
  roles:
  - role: common
  remote_user: ec2-user
  become: yes
  
- hosts: cluster_master
  roles:
  - role: cm
  remote_user: ec2-user
  become: yes
  
- hosts: indexer
  roles:
  - role: idx
  remote_user: ec2-user
  become: yes

- hosts: search_head
  roles:
  - role: sh
  remote_user: ec2-user
  become: yes

- name: start services
  hosts: all
  remote_user: ec2-user
  become: yes

  gather_facts: yes

  tasks:
  - name: Start Splunk Service
    command: /opt/splunk/bin/splunk start
    become: true
    become_user: splunk
